name: Docker Build and Push

description: Docker Compose Build and Push to registery.

inputs:
  REGISTRY:
    description: Docker image registery.
    required: true
    default: ghcr.io
  registry_username:
    description: Docker image registery username.
    required: true
    default: ${{ github.actor }}
  registry_password:
    description: Docker image registery password.
    required: true
  IMAGE_NAME:
    description: Image name
    required: true
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}
        labels: |
          org.opencontainers.image.description=${{ env.branch }}.${{ env.sha_short }} ${{ github.event.head_commit.message }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/bake-action@v6
      with:
        source: .
        push: true
        # set: |
        #   *.labels=${{ steps.meta.outputs.labels }}
        #   *.tags=${{ steps.meta.outputs.tags }}
