name: Docker Build and Push

description: Docker Compose Build and Push to registery.

inputs:
  registry:
    description: Docker image registery.
    required: true
    default: ghcr.io
  registry_username:
    description: Docker image registery username.
    required: true
    default: ${{ github.actor }}
  registry_password:
    description: Docker image registery password.
    required: true
  project:
    description: Image name
    required: true
    default: ${{ github.repository }}
  service:
    description: Service name
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.project }}
        tags: ${{ github.ref_name }}
        labels: |
          org.opencontainers.image.description=${{ github.ref_name }}.${{ github.sha }} ${{ github.event.head_commit.message }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/bake-action@v6
      with:
        set: |
          *.tags=${{ steps.meta.outputs.tags }}
        targets: ${{ inputs.service }}
        push: true
